aur-fetch: remove AUR_SEEN
Discussion around AUR_SEEN has stalled the 3.0 release for months, let's
just leave it out and use the 2.3 behavior + extras.

This removes the need for flags like --existing, --confirm-seen and
other complex logic.

diff --git a/lib/aur-fetch b/lib/aur-fetch
--- a/lib/aur-fetch
+++ b/lib/aur-fetch
@@ -6,19 +6,15 @@ AUR_LOCATION=${AUR_LOCATION:-https://aur.archlinux.org}
 XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
 PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[1]}(): }'
 
-# default arguments
-pull_args=('--verbose')
-diff_args=('--patch' '--stat')
-
 # default options
-verbose=0 recurse=0 confirm_seen=0 results=0 sync=no log_fmt=diff
+verbose=0 recurse=0 results=0 sync=no log_fmt=diff
 
 usage() {
     cat <<! | base64 -d
 ICAgICAgICAgICAgIC4tLX5+LF9fCjotLi4uLiwtLS0tLS0tYH5+Jy5fLicKIGAtLCwsICAs
 XyAgICAgIDsnflUnCiAgXywtJyAsJ2AtX187ICctLS4KIChfLyd+fiAgICAgICcnJycoOwoK
 !
-    plain >&2 'usage: %s [-L directory] [-Rrv] pkgname...' "$argv0"
+    plain >&2 'usage: %s [-L directory] [-Srv] pkgname...' "$argv0"
     exit 1
 }
 
@@ -30,7 +26,7 @@ if [[ ! -v NO_COLOR ]] && [[ ! -v AUR_DEBUG ]]; then
 fi
 
 opt_short='rvL:S'
-opt_long=('recurse' 'verbose' 'write-log:' 'confirm-seen' 'sync:' 'results:' 'format:')
+opt_long=('recurse' 'verbose' 'write-log:' 'sync:' 'results:' 'format:')
 opt_hidden=('dump-options')
 
 if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
@@ -38,11 +34,12 @@ if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
 fi
 set -- "${OPTRET[@]}"
 
-unset log_dir
+unset log_dir results_file
 while true; do
     case "$1" in
         -L|--write-log)
-            shift; log_dir=$1 ;;
+            shift
+            log_dir=$1 ;;
         -r|--recurse)
             recurse=1 ;;
         -v|--verbose)
@@ -55,7 +52,7 @@ while true; do
                 auto|reset|rebase|no)
                     sync=$1 ;;
                 *)
-                    error '%s: invalid --sync option: %s' "$argv0" "$1"
+                    error '%s: Invalid --sync option: %s' "$argv0" "$1"
                     usage ;;
             esac ;;
         --format)
@@ -64,13 +61,12 @@ while true; do
                 diff|log)
                     log_fmt=$1 ;;
                 *)
-                    error '%s: invalid --format option: %s' "$argv0" "$1"
+                    error '%s: Invalid --format option: %s' "$argv0" "$1"
                     usage ;;
             esac ;;
-        --confirm-seen)
-            confirm_seen=1 ;;
         --results)
-            shift; results_file=$1 ;;
+            shift
+            results_file=$1 ;;
         --dump-options)
             printf -- '--%s\n' "${opt_long[@]}" ${AUR_DEBUG+"${opt_hidden[@]}"}
             printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g'
@@ -80,13 +76,13 @@ while true; do
     shift
 done
 
-if [[ -v $log_dir ]] && [[ ! -d $log_dir ]]; then
+if [[ -v log_dir ]] && [[ ! -d $log_dir ]]; then
     error '%s: %s: Not a directory' "$argv0" "$log_dir"
     exit 20
 fi
 
 if [[ -v results_file ]]; then
-    : >"$results_file" # truncate file
+    : >"$results_file" || exit 1 # truncate file
     results=1
 fi
 
@@ -95,7 +91,7 @@ if ! (( $# )); then
     exit 1
 fi
 
-# Default to showing PKGBUILD first in patch. (#399)
+# Default to showing PKGBUILD first in patch (#399)
 mkdir -p "$XDG_CONFIG_HOME/aurutils/$argv0"
 orderfile=$XDG_CONFIG_HOME/aurutils/$argv0/orderfile
 
@@ -103,85 +99,91 @@ if [[ ! -s $orderfile ]]; then
     printf 'PKGBUILD\n' > "$orderfile"
 fi
 
-if (( confirm_seen )); then
-    msg >&2 "Marking repositories as seen"
-fi
+# git helper functions
+aur_rebase() {
+    git stash
+    git reset --hard 'HEAD'
+    git rebase --verbose
+}
+aur_reset() {
+    git stash
+    git reset --hard 'HEAD@{upstream}'
+}
+aur_rev() {
+    git rev-parse --quiet --verify "$1"
+}
 
 if (( recurse )); then
     aur depends --pkgbase "$@"
 else
-   printf '%s\n' "$@"
+    printf '%s\n' "$@"
 fi | while read -r pkg; do
+    # Avoid issues with filesystem boundaries (#274)
+    export GIT_DIR=$pkg/.git GIT_WORK_TREE=$pkg
+
     # Reset/rebase if we are on valid repo
-    if GIT_DIR=$pkg/.git git rev-parse --git-dir >/dev/null 2>&1; then
-        # Avoid issues with filesystem boundaries. (#274)
-        export GIT_DIR=$pkg/.git GIT_WORK_TREE=$pkg
-
-        if (( confirm_seen )); then
-            git update-ref AUR_SEEN HEAD
-
-            msg2 >&2 'Marked repository %s as seen' "$pkg"
-            continue # skip diff logic
+    if [[ -d $pkg ]] && git rev-parse --git-dir >/dev/null; then
+        if ! git fetch --verbose; then
+            exit 1
         fi
 
-        git fetch --verbose >&2 || exit 1
+        head_prev=$(aur_rev 'HEAD')
 
-        case $sync in
-            auto)
-                if [[ $(git config --get --bool aurutils.rebase) == "true" ]]; then
-                    plain >&2 'aurutils.rebase is set for %s' "$pkg"
-                    sync=rebase
+        if [[ $sync == auto ]]; then
+            if [[ $(git config --get --type=bool aurutils.rebase) == 'true' ]]; then
+                plain >&2 'aurutils.rebase is set for %s' "$pkg"
+
+                if ! git merge-base --is-ancestor 'HEAD@{upstream}' 'HEAD'; then
+                    aur_rebase
                 else
-                    sync=reset
-                fi ;;
-        esac
+                    : no new upstream commits
+                fi
+            else
+                if [[ $head_prev != $(aur_rev 'HEAD@{upstream}') ]]; then
+                    aur_reset
+                else
+                    : no new upstream commits
+                fi
+            fi
 
-        case $sync in
-            rebase)
-                git reset --hard 'HEAD' >&2
-                git rebase "${pull_args[@]}" >&2 ;;
-            reset)
-                git reset --hard 'HEAD@{upstream}' >&2 ;;
-        esac || {
+        elif [[ $sync == reset ]] || [[ $sync == rebase ]]; then
+            aur_"$sync"
+
+        elif [[ $sync == no ]]; then
+            : ignore new upstream commits
+        fi || {
             error '%s: %s: Failed to integrate changes' "$argv0" "$pkg"
             exit 1
         }
 
-        if ! seen=$(git rev-parse --quiet --verify AUR_SEEN); then
-            warning '%s: AUR_SEEN object not found for %s, assuming empty tree' "$pkg" "$argv0"
-            seen=$(git hash-object -t tree /dev/null)
-        fi
-
-        if [[ $seen != "$(git rev-parse HEAD)" ]]; then
-            range=${seen:+$seen..}HEAD
-
-            # Contents have changed since last inspection; print differences.
-            if (( verbose )); then
-                git --no-pager "$log_fmt" "${diff_args[@]}" "$range"
-            fi
-
-            if [[ $log_dir ]]; then
-                git --no-pager "$log_fmt" "${diff_args[@]}" "$range" >"$log_dir/$pkg.$log_fmt"
-            fi
-        fi
-
+        # Update results file (fetch)
         if (( results )); then
             printf 'fetch:file://%s\n' "$PWD/$pkg" | tee -a "$results_file"
         fi
 
-    # Otherwise, try to clone anew
-    elif git clone "$AUR_LOCATION/$pkg"; then
-        # Avoid issues with filesystem boundaries. (#274)
-        export GIT_DIR=$pkg/.git GIT_WORK_TREE=$pkg
+        # Print changes from rebase/reset, if any
+        if [[ $head_prev != $(aur_rev 'HEAD') ]]; then
+            range=${head_prev:+$head_prev..}HEAD
 
-        if (( confirm_seen )); then
-            git update-ref AUR_SEEN HEAD
-            msg2 'Marked new repository %s as seen' "$pkg"
+            if (( verbose )); then
+                git --no-pager "$log_fmt" --patch --stat "$range"
+            fi
+
+            if [[ $log_dir ]]; then
+                git --no-pager "$log_fmt" --patch --stat "$range" >"$log_dir/$pkg.$log_fmt"
+            fi
         fi
 
+    elif [[ -d $pkg ]]; then
+        error '%s: %s is not a valid git repository' "$argv0" "$pkg"
+        exit 22
+
+    # Otherwise, try to clone anew
+    elif git clone "$AUR_LOCATION/$pkg" "$GIT_DIR"; then
         # Show PKGBUILDs first. (#399)
         git config diff.orderFile "$orderfile"
 
+        # Update results file (clone)
         if (( results )); then
             printf 'clone:file://%s\n' "$PWD/$pkg" | tee -a "$results_file"
         fi
